using System.Collections.Generic;
using Fluky.Types;

namespace Fluky
{
  public partial class Data
  {
    private IEnumerable<Currency> _currencies;

    /// <summary>
    /// 
    /// </summary>
    public IEnumerable<Currency> Currencies
    {
      get
      {
        if (_currencies != null)
          return _currencies;

        return new List<Currency>
        {
          new Currency(CurrencyCodeType.AED, "United Arab Emirates Dirham"),
          new Currency(CurrencyCodeType.AFN, "Afghanistan Afghani"),
          new Currency(CurrencyCodeType.ALL, "Albania Lek"),
          new Currency(CurrencyCodeType.AMD, "Armenia Dram"),
          new Currency(CurrencyCodeType.ANG, "Netherlands Antilles Guilder"),
          new Currency(CurrencyCodeType.AOA, "Angola Kwanza"),
          new Currency(CurrencyCodeType.ARS, "Argentina Peso"),
          new Currency(CurrencyCodeType.AUD, "Australia Dollar"),
          new Currency(CurrencyCodeType.AWG, "Aruba Guilder"),
          new Currency(CurrencyCodeType.AZN, "Azerbaijan New Manat"),
          new Currency(CurrencyCodeType.BAM, "Bosnia and Herzegovina Convertible Marka"),
          new Currency(CurrencyCodeType.BBD, "Barbados Dollar"),
          new Currency(CurrencyCodeType.BDT, "Bangladesh Taka"),
          new Currency(CurrencyCodeType.BGN, "Bulgaria Lev"),
          new Currency(CurrencyCodeType.BHD, "Bahrain Dinar"),
          new Currency(CurrencyCodeType.BIF, "Burundi Franc"),
          new Currency(CurrencyCodeType.BMD, "Bermuda Dollar"),
          new Currency(CurrencyCodeType.BND, "Brunei Darussalam Dollar"),
          new Currency(CurrencyCodeType.BOB, "Bolivia Boliviano"),
          new Currency(CurrencyCodeType.BRL, "Brazil Real"),
          new Currency(CurrencyCodeType.BSD, "Bahamas Dollar"),
          new Currency(CurrencyCodeType.BTN, "Bhutan Ngultrum"),
          new Currency(CurrencyCodeType.BWP, "Botswana Pula"),
          new Currency(CurrencyCodeType.BYR, "Belarus Ruble"),
          new Currency(CurrencyCodeType.BZD, "Belize Dollar"),
          new Currency(CurrencyCodeType.CAD, "Canada Dollar"),
          new Currency(CurrencyCodeType.CDF, "Congo/Kinshasa Franc"),
          new Currency(CurrencyCodeType.CHF, "Switzerland Franc"),
          new Currency(CurrencyCodeType.CLP, "Chile Peso"),
          new Currency(CurrencyCodeType.CNY, "China Yuan Renminbi"),
          new Currency(CurrencyCodeType.COP, "Colombia Peso"),
          new Currency(CurrencyCodeType.CRC, "Costa Rica Colon"),
          new Currency(CurrencyCodeType.CUC, "Cuba Convertible Peso"),
          new Currency(CurrencyCodeType.CUP, "Cuba Peso"),
          new Currency(CurrencyCodeType.CVE, "Cape Verde Escudo"),
          new Currency(CurrencyCodeType.CZK, "Czech Republic Koruna"),
          new Currency(CurrencyCodeType.DJF, "Djibouti Franc"),
          new Currency(CurrencyCodeType.DKK, "Denmark Krone"),
          new Currency(CurrencyCodeType.DOP, "Dominican Republic Peso"),
          new Currency(CurrencyCodeType.DZD, "Algeria Dinar"),
          new Currency(CurrencyCodeType.EGP, "Egypt Pound"),
          new Currency(CurrencyCodeType.ERN, "Eritrea Nakfa"),
          new Currency(CurrencyCodeType.ETB, "Ethiopia Birr"),
          new Currency(CurrencyCodeType.EUR, "Euro Member Countries"),
          new Currency(CurrencyCodeType.FJD, "Fiji Dollar"),
          new Currency(CurrencyCodeType.FKP, "Falkland Islands (Malvinas) Pound"),
          new Currency(CurrencyCodeType.GBP, "United Kingdom Pound"),
          new Currency(CurrencyCodeType.GEL, "Georgia Lari"),
          new Currency(CurrencyCodeType.GGP, "Guernsey Pound"),
          new Currency(CurrencyCodeType.GHS, "Ghana Cedi"),
          new Currency(CurrencyCodeType.GIP, "Gibraltar Pound"),
          new Currency(CurrencyCodeType.GMD, "Gambia Dalasi"),
          new Currency(CurrencyCodeType.GNF, "Guinea Franc"),
          new Currency(CurrencyCodeType.GTQ, "Guatemala Quetzal"),
          new Currency(CurrencyCodeType.GYD, "Guyana Dollar"),
          new Currency(CurrencyCodeType.HKD, "Hong Kong Dollar"),
          new Currency(CurrencyCodeType.HNL, "Honduras Lempira"),
          new Currency(CurrencyCodeType.HRK, "Croatia Kuna"),
          new Currency(CurrencyCodeType.HTG, "Haiti Gourde"),
          new Currency(CurrencyCodeType.HUF, "Hungary Forint"),
          new Currency(CurrencyCodeType.IDR, "Indonesia Rupiah"),
          new Currency(CurrencyCodeType.ILS, "Israel Shekel"),
          new Currency(CurrencyCodeType.IMP, "Isle of Man Pound"),
          new Currency(CurrencyCodeType.INR, "India Rupee"),
          new Currency(CurrencyCodeType.IQD, "Iraq Dinar"),
          new Currency(CurrencyCodeType.IRR, "Iran Rial"),
          new Currency(CurrencyCodeType.ISK, "Iceland Krona"),
          new Currency(CurrencyCodeType.JEP, "Jersey Pound"),
          new Currency(CurrencyCodeType.JMD, "Jamaica Dollar"),
          new Currency(CurrencyCodeType.JOD, "Jordan Dinar"),
          new Currency(CurrencyCodeType.JPY, "Japan Yen"),
          new Currency(CurrencyCodeType.KES, "Kenya Shilling"),
          new Currency(CurrencyCodeType.KGS, "Kyrgyzstan Som"),
          new Currency(CurrencyCodeType.KHR, "Cambodia Riel"),
          new Currency(CurrencyCodeType.KMF, "Comoros Franc"),
          new Currency(CurrencyCodeType.KPW, "Korea (North) Won"),
          new Currency(CurrencyCodeType.KRW, "Korea (South) Won"),
          new Currency(CurrencyCodeType.KWD, "Kuwait Dinar"),
          new Currency(CurrencyCodeType.KYD, "Cayman Islands Dollar"),
          new Currency(CurrencyCodeType.KZT, "Kazakhstan Tenge"),
          new Currency(CurrencyCodeType.LAK, "Laos Kip"),
          new Currency(CurrencyCodeType.LBP, "Lebanon Pound"),
          new Currency(CurrencyCodeType.LKR, "Sri Lanka Rupee"),
          new Currency(CurrencyCodeType.LRD, "Liberia Dollar"),
          new Currency(CurrencyCodeType.LSL, "Lesotho Loti"),
          new Currency(CurrencyCodeType.LTL, "Lithuania Litas"),
          new Currency(CurrencyCodeType.LYD, "Libya Dinar"),
          new Currency(CurrencyCodeType.MAD, "Morocco Dirham"),
          new Currency(CurrencyCodeType.MDL, "Moldova Leu"),
          new Currency(CurrencyCodeType.MGA, "Madagascar Ariary"),
          new Currency(CurrencyCodeType.MKD, "Macedonia Denar"),
          new Currency(CurrencyCodeType.MMK, "Myanmar (Burma) Kyat"),
          new Currency(CurrencyCodeType.MNT, "Mongolia Tughrik"),
          new Currency(CurrencyCodeType.MOP, "Macau Pataca"),
          new Currency(CurrencyCodeType.MRO, "Mauritania Ouguiya"),
          new Currency(CurrencyCodeType.MUR, "Mauritius Rupee"),
          new Currency(CurrencyCodeType.MVR, "Maldives (Maldive Islands) Rufiyaa"),
          new Currency(CurrencyCodeType.MWK, "Malawi Kwacha"),
          new Currency(CurrencyCodeType.MXN, "Mexico Peso"),
          new Currency(CurrencyCodeType.MYR, "Malaysia Ringgit"),
          new Currency(CurrencyCodeType.MZN, "Mozambique Metical"),
          new Currency(CurrencyCodeType.NAD, "Namibia Dollar"),
          new Currency(CurrencyCodeType.NGN, "Nigeria Naira"),
          new Currency(CurrencyCodeType.NIO, "Nicaragua Cordoba"),
          new Currency(CurrencyCodeType.NOK, "Norway Krone"),
          new Currency(CurrencyCodeType.NPR, "Nepal Rupee"),
          new Currency(CurrencyCodeType.NZD, "New Zealand Dollar"),
          new Currency(CurrencyCodeType.OMR, "Oman Rial"),
          new Currency(CurrencyCodeType.PAB, "Panama Balboa"),
          new Currency(CurrencyCodeType.PEN, "Peru Nuevo Sol"),
          new Currency(CurrencyCodeType.PGK, "Papua New Guinea Kina"),
          new Currency(CurrencyCodeType.PHP, "Philippines Peso"),
          new Currency(CurrencyCodeType.PKR, "Pakistan Rupee"),
          new Currency(CurrencyCodeType.PLN, "Poland Zloty"),
          new Currency(CurrencyCodeType.PYG, "Paraguay Guarani"),
          new Currency(CurrencyCodeType.QAR, "Qatar Riyal"),
          new Currency(CurrencyCodeType.RON, "Romania New Leu"),
          new Currency(CurrencyCodeType.RSD, "Serbia Dinar"),
          new Currency(CurrencyCodeType.RUB, "Russia Ruble"),
          new Currency(CurrencyCodeType.RWF, "Rwanda Franc"),
          new Currency(CurrencyCodeType.SAR, "Saudi Arabia Riyal"),
          new Currency(CurrencyCodeType.SBD, "Solomon Islands Dollar"),
          new Currency(CurrencyCodeType.SCR, "Seychelles Rupee"),
          new Currency(CurrencyCodeType.SDG, "Sudan Pound"),
          new Currency(CurrencyCodeType.SEK, "Sweden Krona"),
          new Currency(CurrencyCodeType.SGD, "Singapore Dollar"),
          new Currency(CurrencyCodeType.SHP, "Saint Helena Pound"),
          new Currency(CurrencyCodeType.SLL, "Sierra Leone Leone"),
          new Currency(CurrencyCodeType.SOS, "Somalia Shilling"),
          new Currency(CurrencyCodeType.SPL, "Seborga Luigino"),
          new Currency(CurrencyCodeType.SRD, "Suriname Dollar"),
          new Currency(CurrencyCodeType.STD, "São Tomé and Príncipe Dobra"),
          new Currency(CurrencyCodeType.SVC, "El Salvador Colon"),
          new Currency(CurrencyCodeType.SYP, "Syria Pound"),
          new Currency(CurrencyCodeType.SZL, "Swaziland Lilangeni"),
          new Currency(CurrencyCodeType.THB, "Thailand Baht"),
          new Currency(CurrencyCodeType.TJS, "Tajikistan Somoni"),
          new Currency(CurrencyCodeType.TMT, "Turkmenistan Manat"),
          new Currency(CurrencyCodeType.TND, "Tunisia Dinar"),
          new Currency(CurrencyCodeType.TOP, "Tonga Pa\"anga"),
          new Currency(CurrencyCodeType.TRY, "Turkey Lira"),
          new Currency(CurrencyCodeType.TTD, "Trinidad and Tobago Dollar"),
          new Currency(CurrencyCodeType.TVD, "Tuvalu Dollar"),
          new Currency(CurrencyCodeType.TWD, "Taiwan New Dollar"),
          new Currency(CurrencyCodeType.TZS, "Tanzania Shilling"),
          new Currency(CurrencyCodeType.UAH, "Ukraine Hryvnia"),
          new Currency(CurrencyCodeType.UGX, "Uganda Shilling"),
          new Currency(CurrencyCodeType.USD, "United States Dollar"),
          new Currency(CurrencyCodeType.UYU, "Uruguay Peso"),
          new Currency(CurrencyCodeType.UZS, "Uzbekistan Som"),
          new Currency(CurrencyCodeType.VEF, "Venezuela Bolivar"),
          new Currency(CurrencyCodeType.VND, "Viet Nam Dong"),
          new Currency(CurrencyCodeType.VUV, "Vanuatu Vatu"),
          new Currency(CurrencyCodeType.WST, "Samoa Tala"),
          new Currency(CurrencyCodeType.XAF, "Communauté Financière Africaine (BEAC) CFA Franc BEAC"),
          new Currency(CurrencyCodeType.XCD, "East Caribbean Dollar"),
          new Currency(CurrencyCodeType.XDR, "International Monetary Fund (IMF) Special Drawing Rights"),
          new Currency(CurrencyCodeType.XOF, "Communauté Financière Africaine (BCEAO) Franc"),
          new Currency(CurrencyCodeType.XPF, "Comptoirs Français du Pacifique (CFP) Franc"),
          new Currency(CurrencyCodeType.YER, "Yemen Rial"),
          new Currency(CurrencyCodeType.ZAR, "South Africa Rand"),
          new Currency(CurrencyCodeType.ZMW, "Zambia Kwacha"),
          new Currency(CurrencyCodeType.ZWD, "Zimbabwe Dollar")
        };
      }
      set { _currencies = value; }
    }
  }
}
